export enum Colors{
    'lightcoral',
    'hotpink',
    'coral',
    'palegoldenrod',
    'slateblue',
    'mediumseagreen',
    'cornflowerblue',
    'firebrick',
    'mediumvioletred',
    'tomato',
    'darkkhaki',
    'orchid',
    'darkslateblue',
    'mediumspringgreen',
    'mediumaquamarine',
    'lightsteelblue',
    'sandybrown'
}