export enum Colors{
    'peachpuff',
    'hotpink',
    'mediumslateblue',
    'lightskyblue',
    'palegoldenrod',
    'aquamarine',
    'teal',
    'royalblue',
    'firebrick',
    'mediumvioletred',
    'tomato',
    'darkkhaki',
    'darkslateblue',
    'mediumspringgreen',
    'lightseagreen',
    'lightsteelblue',
    'darkslategray'
}